language: node_js
node_js:
  - "stable"
cache:
  directories:
    - v2/nstseek.github.io/node_modules
script:
  - cd v2/nstseek.github.io/
  - npm install
  - npm run lint
  - npm run test
  - npm run build
on:
  branch: v2